#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
PROG="/etc/owispmanager/owispmanager.sh"
PROG_NAME="OpenWISP Manager"

start_service() {
        local control_file=/tmp/owispmanager/active
        # avoid reloading while configuration is being applied
        # will wait for a maximum of 30 seconds
        for i in $(seq 1 30); do
                if [ -f $control_file ]; then
                        sleep 1
                else
                        break
                fi
        done
        procd_open_instance
        procd_set_param command $PROG 
        procd_set_param respawn
        procd_close_instance
        logger -s -t owispmanager \
               -p daemon.info \
               "$PROG_NAME started" 
}

service_triggers() {
        procd_add_reload_trigger owispmanager
}

stop_service() {
        logger -s "$PROG_NAME stopping" \
               -t owispmanager \
               -p daemon.info
}

reload_service() {
        logger -s -t owispmanager \
               -p daemon.info \
               "$PROG_NAME received reload trigger"
        # reload
        restart
}
